import './globals.css'
import { Sofia_Sans } from 'next/font/google'

const sofia = Sofia_Sans({ 
  subsets: ['latin'],
  variable: '--font-sofia',
  weight: ['200', '700']
  })

export const metadata = {
  title: 'Portfollio Carlos Junior',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sofia.className}>{children}</body>
    </html>
  )
}
